/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rpglegacy.view;

import com.mycompany.rpglegacy.controller.RPGController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Windows10
 */
public class CadastrarUsuario extends javax.swing.JPanel {
    RPGController controller;
    /**
     * Creates new form CadastrarUsuario
     */
    public CadastrarUsuario() {
        initComponents();
        this.bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wooden_board.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarButton = new javax.swing.JButton();
        cadastroPanel = new javax.swing.JPanel();
        cadastroLabel = new javax.swing.JLabel();
        cadastroTextField = new javax.swing.JTextField();
        cadastrarButton = new javax.swing.JButton();
        senhaPassField = new javax.swing.JPasswordField();
        erroLabel = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        cadastroPanel.setBackground(new java.awt.Color(220, 220, 220));
        cadastroPanel.setMaximumSize(new java.awt.Dimension(300, 350));
        cadastroPanel.setMinimumSize(new java.awt.Dimension(300, 350));
        cadastroPanel.setOpaque(false);
        cadastroPanel.setPreferredSize(new java.awt.Dimension(300, 350));
        cadastroPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastroLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cadastroLabel.setText("CADASTRO");
        cadastroPanel.add(cadastroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        cadastroTextField.setMaximumSize(new java.awt.Dimension(200, 32));
        cadastroTextField.setMinimumSize(new java.awt.Dimension(200, 32));
        cadastroTextField.setPreferredSize(new java.awt.Dimension(200, 32));
        cadastroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroTextFieldActionPerformed(evt);
            }
        });
        cadastroPanel.add(cadastroTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        cadastrarButton.setText("SIGN UP");
        cadastrarButton.setMaximumSize(new java.awt.Dimension(200, 32));
        cadastrarButton.setMinimumSize(new java.awt.Dimension(200, 32));
        cadastrarButton.setOpaque(true);
        cadastrarButton.setPreferredSize(new java.awt.Dimension(200, 32));
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        cadastroPanel.add(cadastrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        senhaPassField.setMaximumSize(new java.awt.Dimension(200, 32));
        senhaPassField.setMinimumSize(new java.awt.Dimension(200, 32));
        senhaPassField.setPreferredSize(new java.awt.Dimension(200, 32));
        senhaPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPassFieldActionPerformed(evt);
            }
        });
        cadastroPanel.add(senhaPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        erroLabel.setForeground(new java.awt.Color(255, 0, 0));
        erroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastroPanel.add(erroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 62, 256, 15));

        bgLabel.setMaximumSize(new java.awt.Dimension(300, 350));
        bgLabel.setMinimumSize(new java.awt.Dimension(300, 350));
        bgLabel.setPreferredSize(new java.awt.Dimension(300, 350));
        cadastroPanel.add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(cadastroPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        controller.irTelaPrincipal();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        controller.cadastrarUsuario();
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void cadastroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroTextFieldActionPerformed
        controller.autenticarUsuario();
    }//GEN-LAST:event_cadastroTextFieldActionPerformed

    private void senhaPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPassFieldActionPerformed
        controller.autenticarUsuario();
    }//GEN-LAST:event_senhaPassFieldActionPerformed

    public JButton getCadastrarButton() {
        return cadastrarButton;
    }

    public JPasswordField getSenhaPassField() {
        return senhaPassField;
    }


    public JTextField getCadastroTextField() {
        return cadastroTextField;
    }

    public JButton getVoltarButton() {
        return voltarButton;
    }

    public JLabel getErroLabel() {
        return erroLabel;
    }
    
    
    public void setController(RPGController controller) {
        this.controller = controller;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JLabel cadastroLabel;
    private javax.swing.JPanel cadastroPanel;
    private javax.swing.JTextField cadastroTextField;
    private javax.swing.JLabel erroLabel;
    private javax.swing.JPasswordField senhaPassField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
