/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rpglegacy.view;

import com.mycompany.rpglegacy.controller.RPGController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Windows10
 */
public class CadastrarUsuario extends javax.swing.JPanel {
    RPGController controller;
    /**
     * Creates new form CadastrarUsuario
     */
    public CadastrarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarButton = new javax.swing.JButton();
        cadastroPanel = new javax.swing.JPanel();
        cadastroLabel = new javax.swing.JLabel();
        cadastroTextField = new javax.swing.JTextField();
        cadastrarButton = new javax.swing.JButton();
        senhaPassField = new javax.swing.JPasswordField();
        erroLabel = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cadastroPanel.setBackground(new java.awt.Color(220, 220, 220));
        cadastroPanel.setPreferredSize(new java.awt.Dimension(300, 350));

        cadastroLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cadastroLabel.setText("CADASTRO");

        cadastroTextField.setMaximumSize(new java.awt.Dimension(256, 64));
        cadastroTextField.setMinimumSize(new java.awt.Dimension(256, 64));
        cadastroTextField.setPreferredSize(new java.awt.Dimension(256, 64));
        cadastroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroTextFieldActionPerformed(evt);
            }
        });

        cadastrarButton.setText("SIGN UP");
        cadastrarButton.setMaximumSize(new java.awt.Dimension(256, 64));
        cadastrarButton.setMinimumSize(new java.awt.Dimension(256, 64));
        cadastrarButton.setOpaque(true);
        cadastrarButton.setPreferredSize(new java.awt.Dimension(256, 64));
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        senhaPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPassFieldActionPerformed(evt);
            }
        });

        erroLabel.setForeground(new java.awt.Color(255, 0, 0));
        erroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout cadastroPanelLayout = new javax.swing.GroupLayout(cadastroPanel);
        cadastroPanel.setLayout(cadastroPanelLayout);
        cadastroPanelLayout.setHorizontalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                        .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                        .addComponent(cadastroLabel)
                        .addGap(96, 96, 96))))
        );
        cadastroPanelLayout.setVerticalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cadastroLabel)
                .addGap(15, 15, 15)
                .addComponent(erroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(senhaPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(cadastroPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        controller.irTelaPrincipal();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        controller.cadastrarUsuario();
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void cadastroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroTextFieldActionPerformed
        controller.autenticarUsuario();
    }//GEN-LAST:event_cadastroTextFieldActionPerformed

    private void senhaPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPassFieldActionPerformed
        controller.autenticarUsuario();
    }//GEN-LAST:event_senhaPassFieldActionPerformed

    public JButton getCadastrarButton() {
        return cadastrarButton;
    }

    public JPasswordField getSenhaPassField() {
        return senhaPassField;
    }


    public JTextField getCadastroTextField() {
        return cadastroTextField;
    }

    public JButton getVoltarButton() {
        return voltarButton;
    }

    public JLabel getErroLabel() {
        return erroLabel;
    }
    
    
    public void setController(RPGController controller) {
        this.controller = controller;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JLabel cadastroLabel;
    private javax.swing.JPanel cadastroPanel;
    private javax.swing.JTextField cadastroTextField;
    private javax.swing.JLabel erroLabel;
    private javax.swing.JPasswordField senhaPassField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
