/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rpglegacy.view;

import com.mycompany.rpglegacy.controller.RPGController;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Windows10
 */
public class CarregarPersonagem extends javax.swing.JPanel {
    RPGController controller;
    /**
     * Creates new form CarregarPersonagem
     */
    public CarregarPersonagem() {
        initComponents();
        this.listaHerois.setFixedCellHeight(75);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaHeroisPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaHerois = new javax.swing.JList<>();
        statusHeroiPanel = new javax.swing.JPanel();
        spriteHeroiPanel = new javax.swing.JPanel();
        ListHeaderPanel = new javax.swing.JPanel();
        ListNameHeaderLabel = new javax.swing.JLabel();
        ListNameHeaderLabel1 = new javax.swing.JLabel();
        ListNameHeaderLabel2 = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(640, 480));

        listaHeroisPanel.setBackground(new java.awt.Color(232, 232, 232));
        listaHeroisPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escolha um Heroi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        listaHeroisPanel.setMaximumSize(new java.awt.Dimension(400, 400));
        listaHeroisPanel.setMinimumSize(new java.awt.Dimension(400, 400));
        listaHeroisPanel.setPreferredSize(new java.awt.Dimension(400, 400));

        listaHerois.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        listaHerois.setAutoscrolls(false);
        jScrollPane2.setViewportView(listaHerois);

        javax.swing.GroupLayout spriteHeroiPanelLayout = new javax.swing.GroupLayout(spriteHeroiPanel);
        spriteHeroiPanel.setLayout(spriteHeroiPanelLayout);
        spriteHeroiPanelLayout.setHorizontalGroup(
            spriteHeroiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        spriteHeroiPanelLayout.setVerticalGroup(
            spriteHeroiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout statusHeroiPanelLayout = new javax.swing.GroupLayout(statusHeroiPanel);
        statusHeroiPanel.setLayout(statusHeroiPanelLayout);
        statusHeroiPanelLayout.setHorizontalGroup(
            statusHeroiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusHeroiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spriteHeroiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusHeroiPanelLayout.setVerticalGroup(
            statusHeroiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusHeroiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spriteHeroiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ListHeaderPanel.setBackground(new java.awt.Color(255, 255, 255));
        ListHeaderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ListNameHeaderLabel.setText("Nome");

        ListNameHeaderLabel1.setText("Level");

        ListNameHeaderLabel2.setText("Progresso");

        javax.swing.GroupLayout ListHeaderPanelLayout = new javax.swing.GroupLayout(ListHeaderPanel);
        ListHeaderPanel.setLayout(ListHeaderPanelLayout);
        ListHeaderPanelLayout.setHorizontalGroup(
            ListHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListHeaderPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ListNameHeaderLabel)
                .addGap(100, 100, 100)
                .addComponent(ListNameHeaderLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(ListNameHeaderLabel2)
                .addContainerGap())
        );
        ListHeaderPanelLayout.setVerticalGroup(
            ListHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListNameHeaderLabel)
                    .addComponent(ListNameHeaderLabel1)
                    .addComponent(ListNameHeaderLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout listaHeroisPanelLayout = new javax.swing.GroupLayout(listaHeroisPanel);
        listaHeroisPanel.setLayout(listaHeroisPanelLayout);
        listaHeroisPanelLayout.setHorizontalGroup(
            listaHeroisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaHeroisPanelLayout.createSequentialGroup()
                .addGroup(listaHeroisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(ListHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusHeroiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        listaHeroisPanelLayout.setVerticalGroup(
            listaHeroisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaHeroisPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(listaHeroisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(statusHeroiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(listaHeroisPanelLayout.createSequentialGroup()
                        .addComponent(ListHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarButton)
                .addGap(18, 18, 18)
                .addComponent(listaHeroisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaHeroisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voltarButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        controller.irTelaPrincipal();
    }//GEN-LAST:event_voltarButtonActionPerformed

    public void setController(RPGController controller) {
        this.controller = controller;
    }

    public JList<String> getListaHerois() {
        return listaHerois;
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListHeaderPanel;
    private javax.swing.JLabel ListNameHeaderLabel;
    private javax.swing.JLabel ListNameHeaderLabel1;
    private javax.swing.JLabel ListNameHeaderLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaHerois;
    private javax.swing.JPanel listaHeroisPanel;
    private javax.swing.JPanel spriteHeroiPanel;
    private javax.swing.JPanel statusHeroiPanel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
