/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.mycompany.rpglegacy.view;
    
import com.mycompany.rpglegacy.controller.RPGController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author aluno
 */
public class CriarPersonagem extends javax.swing.JPanel {
    private RPGController controller;
    
    
    /** Creates new form criarPersonagem */
    public CriarPersonagem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        classeComboBox = new javax.swing.JComboBox<>();
        nomeHeroiTextField = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        classeLabel = new javax.swing.JLabel();
        criarHeroiButton = new javax.swing.JButton();
        atributosPanel = new javax.swing.JPanel();
        vidaHeroiLabel = new javax.swing.JLabel();
        atkHeroiLabel = new javax.swing.JLabel();
        defHeroiLabel = new javax.swing.JLabel();
        spdHeroiLabel = new javax.swing.JLabel();
        vidaValorLabel = new javax.swing.JLabel();
        atkValorLabel = new javax.swing.JLabel();
        defValorLabel = new javax.swing.JLabel();
        spdValorLabel = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPanel.setBackground(new java.awt.Color(200, 200, 200));
        tituloPanel.setMaximumSize(new java.awt.Dimension(600, 400));
        tituloPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        tituloPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        tituloLabel.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        tituloLabel.setText("CRIE SEU HEROI!");

        classeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        classeComboBox.setMaximumSize(new java.awt.Dimension(255, 32));
        classeComboBox.setMinimumSize(new java.awt.Dimension(255, 32));
        classeComboBox.setPreferredSize(new java.awt.Dimension(255, 32));
        classeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                classeComboBoxItemStateChanged(evt);
            }
        });
        classeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classeComboBoxActionPerformed(evt);
            }
        });

        nomeHeroiTextField.setMaximumSize(new java.awt.Dimension(256, 32));
        nomeHeroiTextField.setMinimumSize(new java.awt.Dimension(256, 32));
        nomeHeroiTextField.setPreferredSize(new java.awt.Dimension(256, 32));
        nomeHeroiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeHeroiTextFieldActionPerformed(evt);
            }
        });

        nomeLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        nomeLabel.setText("NOME DO HEROI:");

        classeLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        classeLabel.setText("CLASSE DO HEROI:");

        criarHeroiButton.setText("CRIAR");
        criarHeroiButton.setMaximumSize(new java.awt.Dimension(256, 64));
        criarHeroiButton.setMinimumSize(new java.awt.Dimension(256, 64));
        criarHeroiButton.setPreferredSize(new java.awt.Dimension(256, 64));
        criarHeroiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarHeroiButtonActionPerformed(evt);
            }
        });

        atributosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos do Heroi"));

        vidaHeroiLabel.setText("Vida: ");

        atkHeroiLabel.setText("Ataque:");

        defHeroiLabel.setText("Defesa: ");

        spdHeroiLabel.setText("Velociadade: ");

        vidaValorLabel.setText("00");

        atkValorLabel.setText("00");

        defValorLabel.setText("00");

        spdValorLabel.setText("00");

        javax.swing.GroupLayout atributosPanelLayout = new javax.swing.GroupLayout(atributosPanel);
        atributosPanel.setLayout(atributosPanelLayout);
        atributosPanelLayout.setHorizontalGroup(
            atributosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atributosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(atributosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(atributosPanelLayout.createSequentialGroup()
                        .addComponent(vidaHeroiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vidaValorLabel))
                    .addGroup(atributosPanelLayout.createSequentialGroup()
                        .addComponent(spdHeroiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(spdValorLabel))
                    .addGroup(atributosPanelLayout.createSequentialGroup()
                        .addComponent(atkHeroiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atkValorLabel))
                    .addGroup(atributosPanelLayout.createSequentialGroup()
                        .addComponent(defHeroiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(defValorLabel)))
                .addContainerGap())
        );
        atributosPanelLayout.setVerticalGroup(
            atributosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atributosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(atributosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vidaHeroiLabel)
                    .addComponent(vidaValorLabel))
                .addGap(18, 18, 18)
                .addGroup(atributosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atkHeroiLabel)
                    .addComponent(atkValorLabel))
                .addGap(18, 18, 18)
                .addGroup(atributosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defHeroiLabel)
                    .addComponent(defValorLabel))
                .addGap(18, 18, 18)
                .addGroup(atributosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spdHeroiLabel)
                    .addComponent(spdValorLabel))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        voltarButton.setText("Voltar");

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tituloPanelLayout.createSequentialGroup()
                        .addComponent(tituloLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tituloPanelLayout.createSequentialGroup()
                        .addComponent(atributosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addGroup(tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeHeroiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(classeLabel)
                                .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomeLabel))
                            .addGroup(tituloPanelLayout.createSequentialGroup()
                                .addComponent(criarHeroiButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(17, 17, 17))))
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addComponent(nomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tituloPanelLayout.createSequentialGroup()
                        .addComponent(nomeHeroiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(criarHeroiButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(atributosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(voltarButton)
                .addContainerGap())
        );

        add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nomeHeroiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeHeroiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeHeroiTextFieldActionPerformed

    private void criarHeroiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarHeroiButtonActionPerformed
//        controller.criarHeroi();
    }//GEN-LAST:event_criarHeroiButtonActionPerformed

    private void classeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_classeComboBoxItemStateChanged
        System.out.println(this.classeComboBox.getSelectedItem());
    }//GEN-LAST:event_classeComboBoxItemStateChanged

    private void classeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classeComboBoxActionPerformed

    public JButton getVoltarButton() {
        return voltarButton;
    }
    
    public void setController(RPGController controller) {
        this.controller = controller;
    }

    public JLabel getAtkValorLabel() {
        return atkValorLabel;
    }

    public JComboBox<String> getClasseComboBox() {
        return classeComboBox;
    }

    public JButton getCriarHeroiButton() {
        return criarHeroiButton;
    }

    public JLabel getDefValorLabel() {
        return defValorLabel;
    }

    public JLabel getSpdValorLabel() {
        return spdValorLabel;
    }

    public JLabel getVidaValorLabel() {
        return vidaValorLabel;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atkHeroiLabel;
    private javax.swing.JLabel atkValorLabel;
    private javax.swing.JPanel atributosPanel;
    private javax.swing.JComboBox<String> classeComboBox;
    private javax.swing.JLabel classeLabel;
    private javax.swing.JButton criarHeroiButton;
    private javax.swing.JLabel defHeroiLabel;
    private javax.swing.JLabel defValorLabel;
    private javax.swing.JTextField nomeHeroiTextField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel spdHeroiLabel;
    private javax.swing.JLabel spdValorLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JPanel tituloPanel;
    private javax.swing.JLabel vidaHeroiLabel;
    private javax.swing.JLabel vidaValorLabel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables

}
