/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.mycompany.rpglegacy.view;
    
import com.mycompany.rpglegacy.controller.RPGController;

/**
 *
 * @author aluno
 */
public class CriarPersonagem extends javax.swing.JPanel {
    private RPGController controller;
    
    
    /** Creates new form criarPersonagem */
    public CriarPersonagem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        classeComboBox = new javax.swing.JComboBox<>();
        nomeTextField = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        classeLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPanel.setBackground(new java.awt.Color(200, 200, 200));
        tituloPanel.setMaximumSize(new java.awt.Dimension(400, 256));
        tituloPanel.setMinimumSize(new java.awt.Dimension(400, 256));
        tituloPanel.setPreferredSize(new java.awt.Dimension(400, 256));

        tituloLabel.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        tituloLabel.setText("CRIE SEU HEROI!");

        classeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        classeComboBox.setMaximumSize(new java.awt.Dimension(255, 32));
        classeComboBox.setMinimumSize(new java.awt.Dimension(255, 32));
        classeComboBox.setPreferredSize(new java.awt.Dimension(255, 32));

        nomeTextField.setMaximumSize(new java.awt.Dimension(256, 32));
        nomeTextField.setMinimumSize(new java.awt.Dimension(256, 32));
        nomeTextField.setPreferredSize(new java.awt.Dimension(256, 32));
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });

        nomeLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        nomeLabel.setText("NOME DO HEROI:");

        classeLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        classeLabel.setText("NOME DO HEROI:");

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classeLabel)
                    .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel)
                    .addComponent(tituloLabel))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGap(30, 30, 30)
                .addComponent(nomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    public void setController(RPGController controller) {
        this.controller = controller;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> classeComboBox;
    private javax.swing.JLabel classeLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JPanel tituloPanel;
    // End of variables declaration//GEN-END:variables

}
