/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package com.mycompany.rpglegacy.view;

/**
 *
 * @author aluno
 */
public class GameOverDialog extends javax.swing.JDialog {

    /** Creates new form VictoryDialog */
    public GameOverDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vitoriaPanel = new javax.swing.JPanel();
        vitoriaLabel = new javax.swing.JLabel();
        continuarButton = new javax.swing.JButton();
        vidaMaximaPanel = new javax.swing.JPanel();
        infoLabel1 = new javax.swing.JLabel();
        vidaValorLabel = new javax.swing.JLabel();
        adicionadoVidaLabel = new javax.swing.JLabel();
        ataquePanel = new javax.swing.JPanel();
        infoLabel4 = new javax.swing.JLabel();
        ataqueValorLabel = new javax.swing.JLabel();
        adicionadoAtaqueLabel = new javax.swing.JLabel();
        defesaPanel = new javax.swing.JPanel();
        infoLabel5 = new javax.swing.JLabel();
        defesaValorLabel = new javax.swing.JLabel();
        adicionadoDefesaLabel = new javax.swing.JLabel();
        levelPanel = new javax.swing.JPanel();
        infoLabel2 = new javax.swing.JLabel();
        levelValorLabel = new javax.swing.JLabel();
        adicionadoLevelLabel = new javax.swing.JLabel();
        xpPanel = new javax.swing.JPanel();
        infoLabel3 = new javax.swing.JLabel();
        levelValorLabel1 = new javax.swing.JLabel();
        adicionadoLevelLabel1 = new javax.swing.JLabel();
        velocidadePanel = new javax.swing.JPanel();
        infoLabel6 = new javax.swing.JLabel();
        velValorLabel = new javax.swing.JLabel();
        adicionadoVelLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vitoriaPanel.setBackground(new java.awt.Color(204, 0, 0));
        vitoriaPanel.setMaximumSize(new java.awt.Dimension(300, 64));
        vitoriaPanel.setMinimumSize(new java.awt.Dimension(300, 64));
        vitoriaPanel.setPreferredSize(new java.awt.Dimension(300, 64));

        vitoriaLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        vitoriaLabel.setForeground(new java.awt.Color(255, 255, 255));
        vitoriaLabel.setText("GAME OVER!!!");

        javax.swing.GroupLayout vitoriaPanelLayout = new javax.swing.GroupLayout(vitoriaPanel);
        vitoriaPanel.setLayout(vitoriaPanelLayout);
        vitoriaPanelLayout.setHorizontalGroup(
            vitoriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vitoriaPanelLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(vitoriaLabel)
                .addGap(139, 139, 139))
        );
        vitoriaPanelLayout.setVerticalGroup(
            vitoriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vitoriaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vitoriaLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(vitoriaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        continuarButton.setText("SAIR");
        continuarButton.setMaximumSize(new java.awt.Dimension(90, 48));
        continuarButton.setMinimumSize(new java.awt.Dimension(90, 48));
        continuarButton.setPreferredSize(new java.awt.Dimension(90, 48));
        continuarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(continuarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        vidaMaximaPanel.setBackground(new java.awt.Color(255, 255, 255));
        vidaMaximaPanel.setMaximumSize(new java.awt.Dimension(256, 32));
        vidaMaximaPanel.setMinimumSize(new java.awt.Dimension(256, 32));
        vidaMaximaPanel.setPreferredSize(new java.awt.Dimension(256, 32));

        infoLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        infoLabel1.setText("Vida Maxima:");

        vidaValorLabel.setText("Valor da vida");

        adicionadoVidaLabel.setText("adicionado");

        javax.swing.GroupLayout vidaMaximaPanelLayout = new javax.swing.GroupLayout(vidaMaximaPanel);
        vidaMaximaPanel.setLayout(vidaMaximaPanelLayout);
        vidaMaximaPanelLayout.setHorizontalGroup(
            vidaMaximaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vidaMaximaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel1)
                .addGap(18, 18, 18)
                .addComponent(vidaValorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(adicionadoVidaLabel)
                .addGap(31, 31, 31))
        );
        vidaMaximaPanelLayout.setVerticalGroup(
            vidaMaximaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vidaMaximaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vidaMaximaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(adicionadoVidaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, vidaMaximaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(infoLabel1)
                        .addComponent(vidaValorLabel)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(vidaMaximaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 380, -1));

        ataquePanel.setBackground(new java.awt.Color(255, 255, 255));
        ataquePanel.setMaximumSize(new java.awt.Dimension(256, 32));
        ataquePanel.setMinimumSize(new java.awt.Dimension(256, 32));

        infoLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        infoLabel4.setText("Ataque:");

        ataqueValorLabel.setText("Valor ataque");

        adicionadoAtaqueLabel.setText("adicionado");

        javax.swing.GroupLayout ataquePanelLayout = new javax.swing.GroupLayout(ataquePanel);
        ataquePanel.setLayout(ataquePanelLayout);
        ataquePanelLayout.setHorizontalGroup(
            ataquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ataquePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel4)
                .addGap(18, 18, 18)
                .addComponent(ataqueValorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(adicionadoAtaqueLabel)
                .addGap(31, 31, 31))
        );
        ataquePanelLayout.setVerticalGroup(
            ataquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ataquePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ataquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(adicionadoAtaqueLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ataquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(infoLabel4)
                        .addComponent(ataqueValorLabel)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(ataquePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, -1));

        defesaPanel.setBackground(new java.awt.Color(255, 255, 255));
        defesaPanel.setMaximumSize(new java.awt.Dimension(256, 32));
        defesaPanel.setMinimumSize(new java.awt.Dimension(256, 32));

        infoLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        infoLabel5.setText("Defesa:");

        defesaValorLabel.setText("Valor defesa");

        adicionadoDefesaLabel.setText("adicionado");

        javax.swing.GroupLayout defesaPanelLayout = new javax.swing.GroupLayout(defesaPanel);
        defesaPanel.setLayout(defesaPanelLayout);
        defesaPanelLayout.setHorizontalGroup(
            defesaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defesaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel5)
                .addGap(18, 18, 18)
                .addComponent(defesaValorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(adicionadoDefesaLabel)
                .addGap(31, 31, 31))
        );
        defesaPanelLayout.setVerticalGroup(
            defesaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defesaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(defesaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(adicionadoDefesaLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, defesaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(infoLabel5)
                        .addComponent(defesaValorLabel)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(defesaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 380, -1));

        levelPanel.setBackground(new java.awt.Color(255, 255, 255));
        levelPanel.setMaximumSize(new java.awt.Dimension(256, 32));
        levelPanel.setMinimumSize(new java.awt.Dimension(256, 32));

        infoLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        infoLabel2.setText("Level:");

        levelValorLabel.setText("Valor level");

        adicionadoLevelLabel.setText("adicionado");

        javax.swing.GroupLayout levelPanelLayout = new javax.swing.GroupLayout(levelPanel);
        levelPanel.setLayout(levelPanelLayout);
        levelPanelLayout.setHorizontalGroup(
            levelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel2)
                .addGap(18, 18, 18)
                .addComponent(levelValorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(adicionadoLevelLabel)
                .addGap(31, 31, 31))
        );
        levelPanelLayout.setVerticalGroup(
            levelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(levelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(adicionadoLevelLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, levelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(infoLabel2)
                        .addComponent(levelValorLabel)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(levelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 380, -1));

        xpPanel.setBackground(new java.awt.Color(255, 255, 255));
        xpPanel.setMaximumSize(new java.awt.Dimension(256, 32));
        xpPanel.setMinimumSize(new java.awt.Dimension(256, 32));

        infoLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        infoLabel3.setText("XP:");

        levelValorLabel1.setText("Valor Xp");

        adicionadoLevelLabel1.setText("adicionado");

        javax.swing.GroupLayout xpPanelLayout = new javax.swing.GroupLayout(xpPanel);
        xpPanel.setLayout(xpPanelLayout);
        xpPanelLayout.setHorizontalGroup(
            xpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel3)
                .addGap(18, 18, 18)
                .addComponent(levelValorLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(adicionadoLevelLabel1)
                .addGap(31, 31, 31))
        );
        xpPanelLayout.setVerticalGroup(
            xpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(adicionadoLevelLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, xpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(infoLabel3)
                        .addComponent(levelValorLabel1)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(xpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 380, -1));

        velocidadePanel.setBackground(new java.awt.Color(255, 255, 255));
        velocidadePanel.setMaximumSize(new java.awt.Dimension(256, 32));
        velocidadePanel.setMinimumSize(new java.awt.Dimension(256, 32));

        infoLabel6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        infoLabel6.setText("Velocidade:");

        velValorLabel.setText("Valor velocidade");

        adicionadoVelLabel.setText("adicionado");

        javax.swing.GroupLayout velocidadePanelLayout = new javax.swing.GroupLayout(velocidadePanel);
        velocidadePanel.setLayout(velocidadePanelLayout);
        velocidadePanelLayout.setHorizontalGroup(
            velocidadePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(velocidadePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel6)
                .addGap(18, 18, 18)
                .addComponent(velValorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(adicionadoVelLabel)
                .addGap(31, 31, 31))
        );
        velocidadePanelLayout.setVerticalGroup(
            velocidadePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(velocidadePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(velocidadePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(adicionadoVelLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, velocidadePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(infoLabel6)
                        .addComponent(velValorLabel)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(velocidadePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continuarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOverDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOverDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOverDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOverDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameOverDialog dialog = new GameOverDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adicionadoAtaqueLabel;
    private javax.swing.JLabel adicionadoDefesaLabel;
    private javax.swing.JLabel adicionadoLevelLabel;
    private javax.swing.JLabel adicionadoLevelLabel1;
    private javax.swing.JLabel adicionadoVelLabel;
    private javax.swing.JLabel adicionadoVidaLabel;
    private javax.swing.JPanel ataquePanel;
    private javax.swing.JLabel ataqueValorLabel;
    private javax.swing.JButton continuarButton;
    private javax.swing.JPanel defesaPanel;
    private javax.swing.JLabel defesaValorLabel;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel infoLabel2;
    private javax.swing.JLabel infoLabel3;
    private javax.swing.JLabel infoLabel4;
    private javax.swing.JLabel infoLabel5;
    private javax.swing.JLabel infoLabel6;
    private javax.swing.JPanel levelPanel;
    private javax.swing.JLabel levelValorLabel;
    private javax.swing.JLabel levelValorLabel1;
    private javax.swing.JLabel velValorLabel;
    private javax.swing.JPanel velocidadePanel;
    private javax.swing.JPanel vidaMaximaPanel;
    private javax.swing.JLabel vidaValorLabel;
    private javax.swing.JLabel vitoriaLabel;
    private javax.swing.JPanel vitoriaPanel;
    private javax.swing.JPanel xpPanel;
    // End of variables declaration//GEN-END:variables

}
