/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rpglegacy.view;

/**
 *
 * @author Administrador
 */
public class HeroiSprite extends javax.swing.JPanel {

    /**
     * Creates new form HeroiSprite
     */
    public HeroiSprite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heroiProgressBar = new javax.swing.JProgressBar();
        nomeHeroiLabel = new javax.swing.JLabel();
        spriteHeroiLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(128, 200));
        setMinimumSize(new java.awt.Dimension(128, 200));
        setPreferredSize(new java.awt.Dimension(128, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heroiProgressBar.setMaximumSize(new java.awt.Dimension(130, 20));
        heroiProgressBar.setMinimumSize(new java.awt.Dimension(130, 20));
        heroiProgressBar.setPreferredSize(new java.awt.Dimension(130, 20));
        add(heroiProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 182, 130, 20));

        nomeHeroiLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nomeHeroiLabel.setText("jLabel1");
        add(nomeHeroiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        spriteHeroiLabel.setText("sprite");
        add(spriteHeroiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar heroiProgressBar;
    private javax.swing.JLabel nomeHeroiLabel;
    private javax.swing.JLabel spriteHeroiLabel;
    // End of variables declaration//GEN-END:variables
}
