/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rpglegacy.view;

import com.mycompany.rpglegacy.controller.BattleController;
import javax.swing.JLabel;

/**
 *
 * @author aluno
 */
public class InfoPanel extends javax.swing.JPanel {
    private BattleController controller;
    /**
     * Creates new form InfoPanel
     */
    public InfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoTextoLabel = new javax.swing.JLabel();
        botaoTexto = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(620, 70));
        setMinimumSize(new java.awt.Dimension(620, 70));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(620, 70));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoTextoLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        infoTextoLabel.setText("some text rigth here!");
        add(infoTextoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 608, 58));

        botaoTexto.setText("Próximo");
        botaoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTextoActionPerformed(evt);
            }
        });
        add(botaoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTextoActionPerformed
//        controller.proximo();
    }//GEN-LAST:event_botaoTextoActionPerformed

    public void setController(BattleController controller) {
        this.controller = controller;
    }
    
    public JLabel getInfoTextoLabel() {
        return infoTextoLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoTexto;
    private javax.swing.JLabel infoTextoLabel;
    // End of variables declaration//GEN-END:variables
}
