/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rpglegacy.view;

import com.mycompany.rpglegacy.controller.BattleController;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author Administrador
 */
public class PersonagemSprite extends javax.swing.JPanel {
    private BattleController controller;
    /**
     * Creates new form HeroiSprite
     */
    public PersonagemSprite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heroiProgressBar = new javax.swing.JProgressBar();
        spriteHeroiLabel = new javax.swing.JLabel();
        nomeHeroiLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(160, 260));
        setMinimumSize(new java.awt.Dimension(160, 260));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(160, 260));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heroiProgressBar.setForeground(new java.awt.Color(51, 204, 0));
        heroiProgressBar.setMaximum(0);
        heroiProgressBar.setToolTipText("");
        heroiProgressBar.setMaximumSize(new java.awt.Dimension(160, 20));
        heroiProgressBar.setMinimumSize(new java.awt.Dimension(160, 20));
        heroiProgressBar.setPreferredSize(new java.awt.Dimension(160, 20));
        heroiProgressBar.setString("asdasdasd");
        add(heroiProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        spriteHeroiLabel.setMaximumSize(new java.awt.Dimension(148, 200));
        spriteHeroiLabel.setMinimumSize(new java.awt.Dimension(148, 200));
        spriteHeroiLabel.setPreferredSize(new java.awt.Dimension(148, 200));
        add(spriteHeroiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 130));

        nomeHeroiLabel.setBackground(new Color(0,51,255, 40));
        nomeHeroiLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nomeHeroiLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeHeroiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeHeroiLabel.setOpaque(true);
        add(nomeHeroiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 20));
    }// </editor-fold>//GEN-END:initComponents
    
    public void setController(BattleController controller) {
        this.controller = controller;
    }

    public JProgressBar getHeroiProgressBar() {
        return heroiProgressBar;
    }

    public JLabel getNomeHeroiLabel() {
        return nomeHeroiLabel;
    }

    public JLabel getSpriteHeroiLabel() {
        return spriteHeroiLabel;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar heroiProgressBar;
    private javax.swing.JLabel nomeHeroiLabel;
    private javax.swing.JLabel spriteHeroiLabel;
    // End of variables declaration//GEN-END:variables
}
