/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rpglegacy.view;

/**
 *
 * @author aluno
 */
public class TelaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novoJogoButton = new javax.swing.JButton();
        carregarJogoButton = new javax.swing.JButton();
        signInButton = new javax.swing.JButton();
        bolinhaLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(620, 440));
        setMinimumSize(new java.awt.Dimension(620, 440));
        setPreferredSize(new java.awt.Dimension(620, 440));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        novoJogoButton.setText("NOVO JOGO");
        novoJogoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        novoJogoButton.setMaximumSize(new java.awt.Dimension(255, 64));
        novoJogoButton.setMinimumSize(new java.awt.Dimension(255, 64));
        novoJogoButton.setPreferredSize(new java.awt.Dimension(255, 64));
        novoJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoJogoButtonActionPerformed(evt);
            }
        });
        add(novoJogoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        carregarJogoButton.setText("CARREGAR");
        carregarJogoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        carregarJogoButton.setMaximumSize(new java.awt.Dimension(255, 64));
        carregarJogoButton.setMinimumSize(new java.awt.Dimension(255, 64));
        carregarJogoButton.setPreferredSize(new java.awt.Dimension(255, 64));
        carregarJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarJogoButtonActionPerformed(evt);
            }
        });
        add(carregarJogoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        signInButton.setText("SIGN IN");
        signInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInButton.setMaximumSize(new java.awt.Dimension(128, 64));
        signInButton.setMinimumSize(new java.awt.Dimension(64, 64));
        signInButton.setPreferredSize(new java.awt.Dimension(128, 64));
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        bolinhaLabel.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        bolinhaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rpglegacy/view/1200px-Disc_Plain_grey.svg.png"))); // NOI18N
        bolinhaLabel.setText("USUARIO");
        add(bolinhaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signInButtonActionPerformed

    private void carregarJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarJogoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carregarJogoButtonActionPerformed

    private void novoJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoJogoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoJogoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bolinhaLabel;
    private javax.swing.JButton carregarJogoButton;
    private javax.swing.JButton novoJogoButton;
    private javax.swing.JButton signInButton;
    // End of variables declaration//GEN-END:variables
}
