/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rpglegacy.view;

import com.mycompany.rpglegacy.controller.BattleController;

/**
 *
 * @author Administrador
 */
public class TelaBatalha extends javax.swing.JPanel {
    private BattleController controller;
    /**
     * Creates new form Batalha
     */
    public TelaBatalha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarButton5 = new javax.swing.JButton();
        spriteAdversarioPanel = new javax.swing.JPanel();
        nomeHeroiLabel1 = new javax.swing.JLabel();
        spriteHeroiPanel = new javax.swing.JPanel();
        nomeHeroiLabel = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        atacarButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setOpaque(false);

        voltarButton5.setText("Voltar");
        voltarButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton5ActionPerformed(evt);
            }
        });

        spriteAdversarioPanel.setBackground(new java.awt.Color(230, 230, 230));
        spriteAdversarioPanel.setMaximumSize(new java.awt.Dimension(200, 300));
        spriteAdversarioPanel.setMinimumSize(new java.awt.Dimension(200, 300));
        spriteAdversarioPanel.setName(""); // NOI18N

        nomeHeroiLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeHeroiLabel1.setText("jLabel1");

        javax.swing.GroupLayout spriteAdversarioPanelLayout = new javax.swing.GroupLayout(spriteAdversarioPanel);
        spriteAdversarioPanel.setLayout(spriteAdversarioPanelLayout);
        spriteAdversarioPanelLayout.setHorizontalGroup(
            spriteAdversarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spriteAdversarioPanelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(nomeHeroiLabel1)
                .addGap(80, 80, 80))
        );
        spriteAdversarioPanelLayout.setVerticalGroup(
            spriteAdversarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spriteAdversarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeHeroiLabel1)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        spriteHeroiPanel.setBackground(new java.awt.Color(230, 230, 230));
        spriteHeroiPanel.setMaximumSize(new java.awt.Dimension(200, 300));
        spriteHeroiPanel.setMinimumSize(new java.awt.Dimension(200, 300));
        spriteHeroiPanel.setName(""); // NOI18N
        spriteHeroiPanel.setPreferredSize(new java.awt.Dimension(200, 300));

        nomeHeroiLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeHeroiLabel.setText("jLabel1");

        javax.swing.GroupLayout spriteHeroiPanelLayout = new javax.swing.GroupLayout(spriteHeroiPanel);
        spriteHeroiPanel.setLayout(spriteHeroiPanelLayout);
        spriteHeroiPanelLayout.setHorizontalGroup(
            spriteHeroiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spriteHeroiPanelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(nomeHeroiLabel)
                .addGap(80, 80, 80))
        );
        spriteHeroiPanelLayout.setVerticalGroup(
            spriteHeroiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spriteHeroiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeHeroiLabel)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        infoPanel.setBackground(new java.awt.Color(220, 220, 220));
        infoPanel.setMaximumSize(new java.awt.Dimension(512, 64));
        infoPanel.setMinimumSize(new java.awt.Dimension(512, 64));
        infoPanel.setPreferredSize(new java.awt.Dimension(512, 64));

        infoLabel.setText("jLabel1");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(infoLabel)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(infoLabel)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        atacarButton.setBackground(new java.awt.Color(240, 240, 240));
        atacarButton.setText("jButton1");
        atacarButton.setMaximumSize(new java.awt.Dimension(200, 64));
        atacarButton.setMinimumSize(new java.awt.Dimension(200, 64));
        atacarButton.setPreferredSize(new java.awt.Dimension(200, 64));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarButton5)
                .addGap(31, 31, 31)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atacarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spriteHeroiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spriteAdversarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voltarButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spriteHeroiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spriteAdversarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atacarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton5ActionPerformed
//        controller.irTelaPrincipal();
    }//GEN-LAST:event_voltarButton5ActionPerformed

    public void setController(BattleController controller) {
        this.controller = controller;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atacarButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel nomeHeroiLabel;
    private javax.swing.JLabel nomeHeroiLabel1;
    private javax.swing.JPanel spriteAdversarioPanel;
    private javax.swing.JPanel spriteHeroiPanel;
    private javax.swing.JButton voltarButton5;
    // End of variables declaration//GEN-END:variables
}
