/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rpglegacy.view;

import com.mycompany.rpglegacy.controller.BattleController;

/**
 *
 * @author Administrador
 */
public class TelaBatalha extends javax.swing.JPanel {
    private BattleController controller;
    /**
     * Creates new form Batalha
     */
    public TelaBatalha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarButton5 = new javax.swing.JButton();
        spriteAdversarioPanel = new javax.swing.JPanel();
        nomeAdversarioLabel = new javax.swing.JLabel();
        spriteHeroiPanel = new javax.swing.JPanel();
        nomeHeroiLabel = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        atacarButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarButton5.setText("Voltar");
        voltarButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton5ActionPerformed(evt);
            }
        });
        add(voltarButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        spriteAdversarioPanel.setBackground(new java.awt.Color(230, 230, 230));
        spriteAdversarioPanel.setMaximumSize(new java.awt.Dimension(300, 300));
        spriteAdversarioPanel.setMinimumSize(new java.awt.Dimension(300, 300));
        spriteAdversarioPanel.setName(""); // NOI18N
        spriteAdversarioPanel.setPreferredSize(new java.awt.Dimension(300, 300));

        nomeAdversarioLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeAdversarioLabel.setText("jLabel1");

        javax.swing.GroupLayout spriteAdversarioPanelLayout = new javax.swing.GroupLayout(spriteAdversarioPanel);
        spriteAdversarioPanel.setLayout(spriteAdversarioPanelLayout);
        spriteAdversarioPanelLayout.setHorizontalGroup(
            spriteAdversarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spriteAdversarioPanelLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(nomeAdversarioLabel)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        spriteAdversarioPanelLayout.setVerticalGroup(
            spriteAdversarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spriteAdversarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeAdversarioLabel)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        add(spriteAdversarioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        spriteHeroiPanel.setBackground(new java.awt.Color(230, 230, 230));
        spriteHeroiPanel.setMaximumSize(new java.awt.Dimension(200, 300));
        spriteHeroiPanel.setMinimumSize(new java.awt.Dimension(200, 300));
        spriteHeroiPanel.setName(""); // NOI18N
        spriteHeroiPanel.setPreferredSize(new java.awt.Dimension(200, 300));

        nomeHeroiLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeHeroiLabel.setText("jLabel1");

        javax.swing.GroupLayout spriteHeroiPanelLayout = new javax.swing.GroupLayout(spriteHeroiPanel);
        spriteHeroiPanel.setLayout(spriteHeroiPanelLayout);
        spriteHeroiPanelLayout.setHorizontalGroup(
            spriteHeroiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spriteHeroiPanelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(nomeHeroiLabel)
                .addGap(80, 80, 80))
        );
        spriteHeroiPanelLayout.setVerticalGroup(
            spriteHeroiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spriteHeroiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeHeroiLabel)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        add(spriteHeroiPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 88, -1, -1));

        infoPanel.setBackground(new java.awt.Color(220, 220, 220));
        infoPanel.setMaximumSize(new java.awt.Dimension(512, 64));
        infoPanel.setMinimumSize(new java.awt.Dimension(512, 64));
        infoPanel.setPreferredSize(new java.awt.Dimension(512, 64));

        infoLabel.setText("jLabel1");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(infoLabel)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(infoLabel)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 6, -1, -1));

        atacarButton.setBackground(new java.awt.Color(240, 240, 240));
        atacarButton.setText("jButton1");
        atacarButton.setMaximumSize(new java.awt.Dimension(200, 64));
        atacarButton.setMinimumSize(new java.awt.Dimension(200, 64));
        atacarButton.setPreferredSize(new java.awt.Dimension(200, 64));
        add(atacarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton5ActionPerformed
//        controller.irTelaPrincipal();
    }//GEN-LAST:event_voltarButton5ActionPerformed

    public void setController(BattleController controller) {
        this.controller = controller;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atacarButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel nomeAdversarioLabel;
    private javax.swing.JLabel nomeHeroiLabel;
    private javax.swing.JPanel spriteAdversarioPanel;
    private javax.swing.JPanel spriteHeroiPanel;
    private javax.swing.JButton voltarButton5;
    // End of variables declaration//GEN-END:variables
}
